### ISSUE TITLE
Why debian 10 support removed without any reason / related commit message? invalid

### ISSUE THREAD

**Issue by azzamsa** [frappe/bench#1045]
This PR https://github.com/frappe/bench/pull/872 add a support for Debian 10.

But then it's removed https://github.com/frappe/bench/blob/develop/install.py#L82.

Two previous commit doesn't state the reason.

Thank you

**Comment by gavindsouza** [comment]
The PR https://github.com/frappe/bench/pull/880 overwrote some of the changes made by the former. Dropping support for Debian 10 wasn't a decision but an error during the Playbooks restructure 8 months ago. 

Moreover, support wasn't dropped if you check the diffs of the playbooks then and now. The script might say that it doesn't support Debian 10 yet, but does the script still work for you? Because apart from the text printed, the playbooks are still supposed to be compatible.
