### ISSUE TITLE
Production Installation Failure on Ubuntu Server 16 LTS ( info_egg )

### ISSUE THREAD

**Issue by adam-je** [frappe/bench#356]
I've been trying to setup ERPNext on EC2 for 2 days now, after over 10 attempts, 0 success!
I've tried different PHP versions, PIP addons (setuptools), python-mysqldb setup, etc on Ubuntu 14 and Ubuntu 16.

On https://github.com/frappe/bench
I cant get past the frappe installation. 

1. The easy setup script is getting stuck at with a the error:
- _**no hosts available**_ related to ansible
- Related to issue https://github.com/frappe/bench/issues/336

2. While the manual setup is failing at the error: 
- _**Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-e8Q0ZW/mysql-python/**_

Terminal:

```
1. frappe@ip-172-31-21-146:~$ bench init frappe-bench && cd frappe-bench
2. Already using interpreter /usr/bin/python
3. INFO:bench.app:getting app frappe
4. Cloning into 'frappe'...
5. remote: Counting objects: 1979, done.
6. remote: Compressing objects: 100% (1829/1829), done.
7. remote: Total 1979 (delta 269), reused 771 (delta 95), pack-reused 0
8. Receiving objects: 100% (1979/1979), 12.59 MiB | 3.65 MiB/s, done.
9. Resolving deltas: 100% (269/269), done.
10. Checking connectivity... done.
11. installing frappe
12. INFO:bench.app:installing frappe
13. Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-iwmeai/mysql-python/
14. Traceback (most recent call last):
15.   File "/usr/local/bin/bench", line 11, in <module>
16.     load_entry_point('bench', 'console_scripts', 'bench')()
17.   File "/home/frappe/bench-repo/bench/cli.py", line 40, in cli
18.     bench_command()
19.   File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 722, in __call__
20.     return self.main(*args, **kwargs)
21.   File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 697, in main
22.     rv = self.invoke(ctx)
23.   File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 1066, in invoke
24.     return _process_result(sub_ctx.command.invoke(sub_ctx))
25.   File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 895, in invoke
26.     return ctx.invoke(self.callback, **ctx.params)
27.   File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 535, in invoke
28.     return callback(*args, **kwargs)
29.   File "/home/frappe/bench-repo/bench/commands/make.py", line 19, in init
30.     verbose=verbose, clone_from=clone_from)
31.   File "/home/frappe/bench-repo/bench/utils.py", line 56, in init
32.     get_app(frappe_path, branch=frappe_branch, bench_path=path, build_asset_files=False, verbose=verbose)
33.   File "/home/frappe/bench-repo/bench/app.py", line 73, in get_app
34.     install_app(app=app_name, bench_path=bench_path, verbose=verbose)
35.   File "/home/frappe/bench-repo/bench/app.py", line 103, in install_app
36.     find_links=find_links))
37.   File "/home/frappe/bench-repo/bench/utils.py", line 127, in exec_cmd
38.     raise CommandFailedError(cmd)
39. bench.utils.CommandFailedError: frappe-bench/env/bin/pip install -q  -e frappe-bench/apps/frappe
40. frappe@ip-172-31-21-146:~$
```

**Comment by fmorato** [comment]
## Solution below
I'm getting the same error on debian 8 aka Jessie and also on testing. 

I got the error running the `bench init frappe-bench && cd frappe-bench` part of the https://github.com/frappe/bench 's README

At the end of your log is the command that failed. `frappe-bench/env/bin/pip install -q  -e frappe-bench/apps/frappe`. The `-q` option stands for `quiet` that's why you can't really find out why that happened.

Running the failing command without the quiet option `frappe-bench/env/bin/pip install -e frappe-bench/apps/frappe` reveals that the failing error occurs during `mysql-python` installation with missing mysql_config: `EnvironmentError: mysql_config not found`. A quick [DuckDuckGo](https://duckduckgo.com/?q=EnvironmentError%3A+mysql_config+not+found) reveals the answer:

    sudo apt-get install libmysqlclient-dev

More references at [StackOverflow](http://stackoverflow.com/questions/5178292/pip-install-mysql-python-fails-with-environmenterror-mysql-config-not-found#5178698)

After this the command runs as expected. Should that package be added as dependency?

**Comment by saurabh6790** [comment]
Fixing via https://github.com/frappe/bench/pull/480
