### ISSUE TITLE
Make bench start to start mariadb and redis first?

### ISSUE THREAD

**Issue by grauschnabel** [frappe/bench#760]
Issue: Feature Request

Hi there,
On my development machine I normaly do not have mariadb and redis running.

Is there a way to configure bench so it starts mariadb (using `systemctl start mariadb`) and redis (also systemctl) first, if the services are not running.

Thanks,
Martin

**Comment by gavindsouza** [comment]
I'm sure you might've figured something out then. Off the top of my head, I could think of a simple bash script which would start mariadb, redis and would also start your process manager (or plainly execute "bench start"). You could alias or write a shell function for `bench start` to call your script instead of bench directly.
