### ISSUE TITLE
"UTF-8 locale which is recommended" error & it's workaround.

### ISSUE THREAD

**Issue by asharamseervi** [frappe/bench#891]
I would like to report a strange bug, which I noticed while installing ERPNext with easy install after python-3 commits.

Every dependencies was successfully installed, to the Ubuntu 18.04 VM at Microsoft Azure. I got install.py script via wget. While hitting `sudo python3 install.py --production --user frappe` command has returned error as follows:
```
frappe@erpnext:~$ sudo python3 install.py --production --user frappe
[sudo] password for frappe:
Logs are saved under /tmp/logs/install_bench.log
Checking System Compatibility...
ubuntu 18 is compatible!
Bench's CLI needs these to be defined!
Run the following commands in shell:
export LC_ALL=C.UTF-8
frappe@erpnext:~$ 
```
As error suggests solution itself, hit `$ export LC_ALL=C.UTF-8` command in terminal, after rebooting VM, following command `$ sudo python3 install.py --production --user frappe` worked like charm.

This not ends here, while enabling multi-tenancy, by hitting command: `$ bench config dns_multitenant on` returning similar error as below:

```
frappe@erpnext:~/frappe-bench$ bench config dns_multitenant on
Traceback (most recent call last):
  File "/usr/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/utils/bench_helper.py", line 97, in <module>
    main()
  File "/home/frappe/frappe-bench/apps/frappe/frappe/utils/bench_helper.py", line 18, in main
    click.Group(commands=commands)(prog_name='bench')
  File "/home/frappe/frappe-bench/env/lib/python3.6/site-packages/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "/home/frappe/frappe-bench/env/lib/python3.6/site-packages/click/core.py", line 696, in main
    _verify_python3_env()
  File "/home/frappe/frappe-bench/env/lib/python3.6/site-packages/click/_unicodefun.py", line 124, in _verify_python3_env
    ' mitigation steps.' + extra
RuntimeError: Click will abort further execution because Python 3 was configured to use ASCII as encoding for the environment. Consult https://click.palletsprojects.com                                                                     /en/7.x/python3/ for mitigation steps.

This system supports the C.UTF-8 locale which is recommended.
You might be able to resolve your issue by exporting the
following environment variables:

    export LC_ALL=C.UTF-8
    export LANG=C.UTF-8

Traceback (most recent call last):
  File "/usr/local/bin/bench", line 11, in <module>
    load_entry_point('bench', 'console_scripts', 'bench')()
  File "/home/frappe/.bench/bench/cli.py", line 40, in cli
    bench_command()
  File "/usr/local/lib/python3.6/dist-packages/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/click/core.py", line 696, in main
    _verify_python3_env()
  File "/usr/local/lib/python3.6/dist-packages/click/_unicodefun.py", line 124, in _verify_python3_env
    ' mitigation steps.' + extra
RuntimeError: Click will abort further execution because Python 3 was configured to use ASCII as encoding for the environment. Consult https://click.palletsprojects.com                                                                     /en/7.x/python3/ for mitigation steps.

This system supports the C.UTF-8 locale which is recommended.
You might be able to resolve your issue by exporting the
following environment variables:

    export LC_ALL=C.UTF-8
    export LANG=C.UTF-8
frappe@erpnext:~/frappe-bench$
```
Again, workaround is self-suggested, by hitting following commands. It will solve issue for once.
```
$ export LC_ALL=C.UTF-8
$ export LANG=C.UTF-8
```

Would like to request contributors & team to provide smoother experience while installing & tinkering with ERPNext. I came back after 1.5 year & 2 major release, but _love of ERPNext towards error is still at peak_.

**Comment by Thunderbottom** [comment]
This is not a bug, but a [requirement for](http://click.palletsprojects.com/en/master/python3/#python-3-surrogate-handling) one of the libraries that we depend on. Most of the UNIX systems that you run will either have these environment variables set or will require you to set them in the system. You can check the current variables set by running `locale` on the command line.

The script runs and checks whether the variables are set and shows a message to set the variables that are missing/required. We cannot have it set for you because the locale might change with region, with `C.UTF-8` being similar to `en-US` based systems, `de_DE.UTF-8` for German systems, and so on. The suggestions to set `C.UTF-8` only comes through because it's safer to ask the user to set the variable to computer-english with basic utf-8 support rather than assume the current locale (which can be done in some ways) and ask the user to export that. I think we can change the prompt to ask the user to set it from a list of detected system locales.   

Understandably, setting variable using `export` from the shell only sets it for the current shell session. You need to append it to the system's locale file, which usually should be `/etc/default/locale`. Once set, the output for running `locale` should be somewhat similar to this:

```bash
➜  ~ locale
LANG=en_US.UTF-8
LC_CTYPE="en_US.UTF-8"
LC_NUMERIC="en_US.UTF-8"
LC_TIME="en_US.UTF-8"
LC_COLLATE="en_US.UTF-8"
LC_MONETARY="en_US.UTF-8"
LC_MESSAGES="en_US.UTF-8"
LC_PAPER="en_US.UTF-8"
LC_NAME="en_US.UTF-8"
LC_ADDRESS="en_US.UTF-8"
LC_TELEPHONE="en_US.UTF-8"
LC_MEASUREMENT="en_US.UTF-8"
LC_IDENTIFICATION="en_US.UTF-8"
LC_ALL=
```

Note that there's no need to set all other `LC_*` variables if you set `LC_ALL` or vice versa.

> Would like to request contributors & team to provide smoother experience while installing & tinkering with ERPNext. I came back after 1.5 year & 2 major release, but _love of ERPNext towards error is still at peak._

I'll disagree with this. The issue that you're pointing out right now doesn't even have anything to do with ERPNext, and we're still trying to help the users out with it. This issue shouldn't even occur in the first place on a system with sane default configuration if you were to ask me.

And if you could've taken some time out to see how helpful the click documentation is, neither of us would've needed to post in here. As funny as it sounds, even the error that click shows you redirects you to their documentation instead of directly handing you the reason for the proposed solution to the error.

```
RuntimeError: Click will abort further execution because Python 3 was configured to use ASCII as encoding for the environment. Consult https://click.palletsprojects.com                                                                     /en/7.x/python3/ for mitigation steps.

This system supports the C.UTF-8 locale which is recommended.
You might be able to resolve your issue by exporting the
following environment variables:

    export LC_ALL=C.UTF-8
    export LANG=C.UTF-8
```

I hope after reading all of this you understand that this error has zilch to do with ERPNext, but is a requirement by one of the libraries and a misconfiguration on the server.

If you have any feedback regarding the installer on where we could improve, feel free to reply to me and hopefully we'll work it out.

**Comment by asharamseervi** [comment]
> My bad, I've reported this. There is nothing to do with ERPNext. Kindly close this issue.

This was my answer before submitting this comment. But, I thought, I've invested 20 minutes to write issue, so does @Thunderbottom !!

- First of all, this issue was faced, while installing & setting-up ERPNext, on fresh Ubuntu 18.04 system.
- Second thing, this was never happened earlier at least to me.
- Third, commit https://github.com/frappe/bench/commit/c7381defd3fcaf447710316db579f3aa7d16ae66#diff-f1887f8e3adfb11d2204ac25baab2d03 have some changes regarding utf. Only after that, I need to hit a few extra commands as mentioned in issue. (That was never existed before this).

That's why, I raised a issue. I agree, that was not bug, but something unusual happened, and as a user I took step forward and reported. Again saying, if this nothing have to do with Bench or it's Requirements or a smoother/better experience, kindly close, that simple.

**Comment by Thunderbottom** [comment]
Please don't get me wrong, but my point is that this issue does not pertain to ERPNext. We're trying to improve our systems, and that's the only reason why we even have a pointer to set those missing environment variables in the first place. 

> Second thing, this was never happened earlier at least to me.

As I stated before, it could be because of a misconfiguration on the server. Sometimes servers don't really come with sane configurations. There's nothing we can do to help but fix it once it shows up.

The commit that you linked unfortunately does not fix anything, but just [changes some existing things](https://github.com/frappe/bench/commit/c7381defd3fcaf447710316db579f3aa7d16ae66#diff-f1887f8e3adfb11d2204ac25baab2d03R34).

Again, I did not mean to be rude. But then again saying that we're more inclined to error than to fixing does make us devs feel bad. All we can do is try to improve the UX from ERPNext's perspective. I don't think we should be held liable for issues that are not caused by us. Feel free to let me know if I'm wrong, and thanks for raising this issue. I hope it clears stuff up for someone else that ever faces this issue.

Also, if you're still ready to help with improving the installation script, let me know and we can work on it.
