### ISSUE TITLE
Incompatible GitPython versions

### ISSUE THREAD

**Issue by barredterra** [frappe/bench#939]
## Reproduce

`bench update --reset` from `v12.2.1` to `v12.3.0`

## Error
```
bench 4.1.0 has requirement GitPython==2.1.11, but you'll have gitpython 2.1.15 which is incompatible.
```

**Comment by gavindsouza** [comment]
Have you tried updating bench's reqs via `pip install -U {path/to/bench-repo}` ?

**Comment by lapphan** [comment]
Temporary work around

> `python3 -m pip install GitPython==2.1.11`

Caused by https://github.com/frappe/bench/pull/938/

**Comment by lapphan** [comment]
After https://github.com/frappe/bench/pull/946/, my above work around doesn't work anymore.
When I call bench command eg. `bench update`, `bench --version`, the mentioned error log appear again and bench did not execute.
>`pkg_resources.DistributionNotFound: The 'GitPython==2.1.11' distribution was not found and is required by bench`

I think the root cause is #938

**Comment by tejpochiraju** [comment]
This seems to be caused by a pinned version difference for GitPython between `root_dir/requirements.txt` and `root_dir/bench.egg-info/requires.txt`. 

I was able to solve this by manually editing `root_dir/bench.egg-info/requires.txt` to mirror the version from `root_dir/requirements.txt`.

[requirements.txt](https://github.com/frappe/bench/files/4301191/requirements.txt)
[requires.txt](https://github.com/frappe/bench/files/4301192/requires.txt)

**Comment by lapphan** [comment]
I managed to fix this bug by running 
>`python3 -m pip install -U --user -e bench`

More detail at https://discuss.erpnext.com/t/bench-error-after-upgrade/58631/8

**Comment by Interconectando** [comment]
I execute this command and worked perfectly.

`sudo pip install --upgrade GitPython==2.1.11`
